import numpy as np
import math as math
from pylab import *
import py.ldpc as ldpc


# Code taken from Adam's python tutorial. 
# I have removed the power allocation code as I'm using a uniform power allocation
# Can get this from the notebook if I decide I need this. 


try:
    from pyfht import fht_inplace
except ImportError:
    import warnings
    warnings.warn("Using very slow Python version of fht, please install pyfht")
    def fht_inplace(x):
        N = len(x)
        i = N>>1
        while i:
            for k in range(0, N, 2*i):
                for j in range(k, i+k):
                    ij = i|j
                    temp = x[j]
                    x[j] += x[ij]
                    x[ij] = temp - x[ij]
            i = i >> 1


def sub_fht(n, m, seed=0, ordering=None):
    """
    Returns functions to compute the sub-sampled Walsh-Hadamard transform,
    i.e., operating with a wide rectangular matrix of random +/-1 entries.

    n: number of rows
    m: number of columns

    It is most efficient (but not required) for max(m+1,n+1) to be a power of 2.

    seed: determines choice of random matrix
    ordering: optional n-long array of row indices in [1, max(m,n)] to
              implement subsampling; generated by seed if not specified,
              but may be given to speed up subsequent runs on the same matrix.

    Returns (Ax, Ay, ordering):
        Ax(x): computes A.x (of length n), with x having length m
        Ay(y): computes A'.y (of length m), with y having length n
        ordering: the ordering in use, which may have been generated from seed
    """
    assert n > 0, "n must be positive"
    assert m > 0, "m must be positive"
    w = 2**int(np.ceil(np.log2(max(m+1, n+1))))

    if ordering is not None:
        assert ordering.shape == (n,)
    else:
        rng = np.random.RandomState(seed)
        idxs = np.arange(1, w, dtype=np.uint32)
        rng.shuffle(idxs)
        ordering = idxs[:n]

    def Ax(x):
        assert x.size == m, "x must be m long"
        y = np.zeros(w)
        y[w-m:] = x.reshape(m)
        fht_inplace(y)
        return y[ordering]

    def Ay(y):
        assert y.size == n, "input must be n long"
        x = np.zeros(w)
        x.flat[ordering] = y
        fht_inplace(x)
        return x[w-m:]

    return Ax, Ay, ordering

def block_sub_fht(n, m, l, seed=0, ordering=None):
    """
    As `sub_fht`, but computes in `l` blocks of size `n` by `m`, potentially
    offering substantial speed improvements.

    n: number of rows
    m: number of columns per block
    l: number of blocks

    It is most efficient (though not required) when max(m+1,n+1) is a power of 2.

    seed: determines choice of random matrix
    ordering: optional (l, n) shaped array of row indices in [1, max(m, n)] to
              implement subsampling; generated by seed if not specified, but
              may be given to speed up subsequent runs on the same matrix.

    Returns (Ax, Ay, ordering):
        Ax(x): computes A.x (of length n), with x having length l*m
        Ay(y): computes A'.y (of length l*m), with y having length n
        ordering: the ordering in use, which may have been generated from seed
    """
    assert n > 0, "n must be positive"
    assert m > 0, "m must be positive"
    assert l > 0, "l must be positive"

    if ordering is not None:
        assert ordering.shape == (l, n)
    else:
        w = 2**int(np.ceil(np.log2(max(m+1, n+1))))
        rng = np.random.RandomState(seed)
        ordering = np.empty((l, n), dtype=np.uint32)
        idxs = np.arange(1, w, dtype=np.uint32)
        for ll in range(l):
            rng.shuffle(idxs)
            ordering[ll] = idxs[:n]
        

    def Ax(x):
        assert x.size == l*m
        out = np.zeros(n)
        for ll in range(l):
            ax, ay, _ = sub_fht(n, m, ordering=ordering[ll])
            out += ax(x[ll*m:(ll+1)*m])
        return out

    def Ay(y):
        assert y.size == n
        out = np.empty(l*m)
        for ll in range(l):
            ax, ay, _ = sub_fht(n, m, ordering=ordering[ll])
            out[ll*m:(ll+1)*m] = ay(y)
        return out

    return Ax, Ay, ordering

#SPARC dictionary
#Returns 2 functions Ab and Az which compute Aβ and A^Tz respectively.
def sparc_transforms(L, M, n):
    Ax, Ay, _ = block_sub_fht(n, M, L, ordering=None)
    def Ab(b):
        return Ax(b).reshape(-1, 1) / np.sqrt(n)
    def Az(z):
        return Ay(z).reshape(-1, 1) / np.sqrt(n)
    return Ab, Az


# the amp algorithm
def amp(y, σ_n, Pl, L, M, T, Ab, Az):
    P = np.sum(Pl)
    n = y.size
    β = np.zeros((L*M, 1))
    z = y
    last_τ = 0
    
    for t in range(T):
        τ = np.sqrt(np.sum(z**2)/n)
        if τ == last_τ:
            return β
        last_τ = τ
        
        s = β + Az(z)
        rt_n_Pl = np.sqrt(n*Pl).repeat(M).reshape(-1, 1)
        u = s * rt_n_Pl / τ**2
        max_u = u.max()
        exps = np.exp(u - max_u)
        sums = exps.reshape(L, M).sum(axis=1).repeat(M).reshape(-1, 1)
        β = (rt_n_Pl * exps / sums).reshape(-1, 1)
        z = y - Ab(β) + (z/τ**2) * (P - np.sum(β**2) / n)
    
    return β

#########End of code from Python Tutorial###########

# SPARC parameters
# l is the number of sections in the overall SPARC
# m is the number of columns per section in the SPARC
# p is the channel signal power, sigma2 is the channel noise power
# r is the user data rate, r_pa the power allocation design rate
# t is the maximum number of AMP iterations permitted
class SPARCParams:
	def __init__(self, L, M, sigma, p, r, r_pa, t):
		self.L = L
		self.M = M
		self.sigma = sigma
		self.p = p
		self.r = r
		self.r_pa = r_pa
		self.t = t

# LDPC Params needed to set up one of Jossy's code
class LDPCParams:
    def __init__(self, standard, r_ldpc, z, ptype='A'):
        self.standard = standard
        self.r_ldpc = r_ldpc
        self.z = z
        self.ptype = ptype


# results of an LDPC simulation
class LDPCResult:
	def __init__(self, errors_after_amp_unprotected, errors_after_amp_protected, errors_after_amp_parity,
		errors_after_ldpc_protected, errors_after_ldpc_parity, errors_after_post_amp_unprotected, iters_amp,
		iters_ldpc, iters_post_amp, ldpc_success):
		self.errors_after_amp_unprotected = errors_after_amp_unprotected
		self.errors_after_amp_protected = errors_after_amp_protected
		self.errors_after_amp_parity = errors_after_amp_parity
		self.errors_after_ldpc_protected = errors_after_ldpc_protected
		self.errors_after_ldpc_parity = errors_after_ldpc_parity
		self.errors_after_post_amp_unprotected = errors_after_post_amp_unprotected
		self.iters_amp = iters_amp
		self.iters_ldpc = iters_ldpc
		self.iters_post_amp = iters_post_amp
		self.ldpc_success = ldpc_success



#function to convert sectionwise probabilities to bitwise probabilities
# note: my sp2bp takes the entire beta vector, whereas adams code works only on 1 section. Change this if neccessary
def sp2bp(β, L, M: "must be power of 2"):
    #take in the section posterior probabilities β.
    #and the no. sections L and the size of each section M. 
    
    #initialise numpy array of zeros for all of the bitwise posteriors
    p = np.zeros(int(np.log2(M)*L))
    #loop through the L sections.
    for a in range(L):
        β_l = β[a*M:((a+1)*M)]
        # normalizing before passing in, so below not needed
        #c = np.sum(β_l) #calculate normalization constant for each section
        for logi in range(int(np.log2(M))):
            b = int((a+1)*np.log2(M) - logi - 1)
            i = 2**logi
            k = i
            while k<M:
                #note shift in range of j due to βl being an array which is indexed from 0 not 1. 
                for j in range(k, k+i):
                    p[b] = p[b] + β_l[j]
                k = k + 2*i
    return p
    



#code has functions which convert bits2bytes, bytes2bits, bits2indices, indices2bits
#not sure if I'll actually need these. If I do someone has probably already written these in  python

# insert bits2bytes fn if needed 

# insert bytes2bits fn if needed 

# insert bits2indices fn.
# assumes that the left most bit (lmb) is the most significant bit (msb)
# note that an input of all zero bits for one section will give an output of 0
# So the first column is being indexed by 0
def bits2indices(bits, m: "m must be a power of 2"):
	
    logm = int(math.log(m,2))
    # assert that the bits can be split exactly into sections of size logm
    assert len(bits)%logm==0
    # find number of sections required for the bits
    sections = int(len(bits)/logm)
    # set up array to store the indices
    indices = []

    for i in range(sections):
        # get the bits corresponding to the current section
        section_bits = bits[i*logm:(i+1)*logm]
        # variable to store the value of the bits in indice
        digit = 0
        for j in range(len(section_bits)):
            if section_bits[j]:
                digit += 2**(len(section_bits)-j-1) 
        indices.append(digit)

    return indices


# insert indices2bits fn if needed 

#Fn to run point-to-point SPARC-AMP simulation with an LDPC outer code protecting the flat sections.
def lpdc_sim(sparcparams: SPARCParams, seed)	-> LDPCResult:	
	#Get the SPARC parameters from the struct
	L = sparcparms.L
	M = sparcparams.M
	p = sparcparams.p
	sigma2 = sparcparams.sigma2
	r = sparcparams.r
	r_pa = sparcparams.r_pa
	t = sparcparams.t


	# pick ldpc code, get it's parameters


	#compute remaining parameters
	logm = int(log(m,2))
	n = int((l * logm - (nl-kl))/r) #nl and kl are the ldpc parameters n and k


	#set up random numbers generator
	np.random.seed(seed)

	#generate random user bits to transmit
	num_sparc_bits = l * logm
	num_user_bits = num_sparc_bits - (nl-kl)
	user_bits = np.random.randint(0, 2, num_user_bits).tolist()

	#split bits into amp bits and those that will be LDPC encoded
	#What are the AMP bits? Aren't all bits AMP decoded.
	amp_bits = user_bits[:(num_user_bits-kl)]
	ldpc_user_bits = user_bits[(num_user_bits-kl):]

	#LPDC encode those bits, via a mapping into bytes and back (this will determine if I need to bytes2bits fns etc.)

	#gather the AMP bits and the LDPC codeword bits (the "SPARC" bits)
	sparc_bits = amp_bits + ldpc_code_bits
	#turn all the SPARC bits into column choices
	#This is when I will need bits2indices
	sparc_indices = bits2indices(sparc_bits, m)


	#Make PA and FHT
	#PA is the power allocation? And FHT is the design matrix?
	#What are these? They are used for next comment. Is one the design matrix?

	#Encode sparc indecs into an actual codeword. 

	#generate channel noise and sum. 

	#Run AMP decoded

	#Gather the hard decision indices

	#Convert indices back to bits

	#Count bit errors in AMP alone. 

	#Convert all column probabilities into bit probabilities.

	#grab the LDPC bit probs, convert to LLRs, decode LDPC codeword

	#Count bit error in LDPC section

	#If LDPC worked, and there are errors in the unprotected bits, try running AMP again

		#Make a new beta_ldpc that only has the ldpc sections set

		#Compute a y that already has all the successfully decoded ldpc sections removed

		#Run AMP over the non-LDPC sections from scratch

		#Gather hard decision indices

	#Convert indices back to bits

	#Count bit errors in AMP unprotected bits

	#RETURN the LDPC results using the above defined struct

def amp_ldpc_sim(sparcparams: SPARCParams, ldpcparams: LDPCParams = None):
    #Get the SPARC parameters from the struct
    L = sparcparams.L
    M = sparcparams.M
    P = sparcparams.p
    sigma = sparcparams.sigma
    r_sparc = sparcparams.r
    r_pa_sparc = sparcparams.r_pa
    T = sparcparams.t

    # calculate some additional parameters 
    # Compute the SNR, capacity, and n, from the input parameters
    snr = P / sigma**2
    #C = 0.5 * np.log2(1 + snr)
    n = int(L*np.log2(M) / r_sparc)
    
    # Generate the power allocation
    # Pl = pa_iterative(L, L, sigma, P, R_PA)
    # uniform power allocation across sections
    Pl = P/L * np.ones(L)
    logm = np.log2(M)

    if ldpcparams == None:
        # set params so that no ldpc encoding or decoding is used
        nl = 0
        kl = 0
        ldpc_bits = []
    else: 
        standard = ldpcparams.standard
        r_ldpc = ldpcparams.r_ldpc
        z = ldpcparams.z
        ptype = ldpcparams.ptype
        # initialise the ldpc code
        ldpc_code = ldpc.code(standard, r_ldpc, z, ptype)
        nl = ldpc_code.N
        kl = ldpc_code.K

        assert nl<=(L*logm)
        # we want the ldpc to cover a complete number of sections and not just part of the final section it covers. 
        assert nl%logm == 0
        #(L, M, sigma, P, R, T, R_PA, R_LDPC):

        # Generate random message in 2 stages
        # First generate ldpc bits
        protected_bits = np.random.randint(0, 2, kl).tolist()
        assert len(protected_bits) == kl

        # Encode the protected_bits using the ldpc code 
        ldpc_bits = ldpc_code.encode(protected_bits).tolist() 

    # Generate the remaining bits required
    unprotected_bits = np.random.randint(0, 2, int(L*logm-nl)).tolist()

    # concatenate the ldpc and unprotected bits
    #if len(ldpc_bits)>0:
        
    sparc_bits = unprotected_bits+ldpc_bits

    assert len(sparc_bits)==int(L*logm)

    # convert the bits to indices for encoding
    sparc_indices = bits2indices(sparc_bits, M)

    assert len(sparc_indices)==L
       
    # Generate the SPARC transform functions A.beta and A'.z
    Ab, Az = sparc_transforms(L, M, n)
    
    # Generate our transmitted signal X
    β_0 = np.zeros((L*M, 1))
    for l in range(L):
        β_0[l*M + sparc_indices[l]] = np.sqrt(n * Pl[l])
    x = Ab(β_0)
    
    # check that the power has been allocated uniformly. This should be approx equal to the snr. 
    print("Average power/snr is ", np.mean(x**2)/snr)

    # Generate random channel noise and then received signal y
    z = np.random.randn(n, 1) * sigma
    y = (x + z).reshape(-1, 1)
        
    # Run AMP decoding
    β = amp(y, sigma, Pl, L, M, T, Ab, Az).reshape(-1)
    # Output the results of just AMP decoding
    
    # Keep below so I can compare it to using the outer ldpc code. Actually below doesn;t work anymore as I generated bits initially. 
    # Convert decoded beta back to a message
    rx_message = []
    for l in range(L):
        idx = np.argmax(β[l*M:(l+1)*M])
        rx_message.append(idx)
    
    # Compute fraction of sections decoded correctly with just AMP decoding
    correct_amp = np.sum(np.array(rx_message) == np.array(sparc_indices)) / L
    print("Fraction of sections decoded correctly with amp: ", correct_amp)
    
    # Compute BER note: np.sum will be deprecated soon, so look up alternative if this code stops working. 
    # DeprecationWarning: Calling np.sum(generator) is deprecated, and in the future will give a different result. Use np.sum(np.from_iter(generator)) or the python sum builtin instead.
    # If this function starts acting weird, look into the above. Or when I transfer this function to my proper code, try to fix this. 
    ber_amp = np.sum(bin(a^b).count('1')
                 for (a, b) in zip(sparc_indices, rx_message))/(L*np.log2(M))

    if ldpcparams==None:
        ber_ldpc = None
    else:
        # Get the sectionwise posterior probabilities by dividing β by the power in each section. 
        # This converts each section in β to a valid probability distribution.
        sectionwise_posterior = β/np.sqrt(n*P/L)


        # convert sectionwise to bitwise posterior probabilities
        bitwise_posterior = sp2bp(sectionwise_posterior, L, M) 
        #print(np.sum(bitwise_posterior))


        # only want to use the bitwise posterior for the sections we've applied the ldpc code to
        # recenter the bitwise posterior around zero for the decoding
        LLR = np.log(1-bitwise_posterior[int((L*logm)-nl):])- np.log(bitwise_posterior[int((L*logm)-nl):])

        (app, it) = ldpc_code.decode(LLR)
        #print((np.ones(nl)/2)-bitwise_posterior[int((L*logm)-nl):])
        test_output = (bitwise_posterior[int((L*logm)-nl):]>0.5)
        print("Incorrect bits before ldpc decoding: ", np.sum(test_output!=ldpc_bits))

        # check that the inequality is the right way round in below
        v_output = (app<0.0)

        print("Incorrect bits in ldpc decoding: ", np.sum(v_output!=ldpc_bits))

        # convert the bits to indices
        beta_output_ldpc = bits2indices(v_output, M)

        beta_output = rx_message
        beta_output[int(L - nl/logm):] = beta_output_ldpc
        print(np.sum(rx_message[int(L - nl/logm):]!= beta_output_ldpc))
        # compute fraction of sections decoded correctly with AMP followed by SPARC decoding
        correct_ldpc = np.sum(np.array(beta_output) == np.array(sparc_indices))/L
        print("Fractions of sections decoded correctly with amp and ldpc: ", correct_ldpc)

            
        # compute BER for amp and ldpc
        ber_ldpc = np.sum(bin(a^b).count('1')
                     for (a, b) in zip(sparc_indices, beta_output))/(L*np.log2(M))

    # Compute Eb/N0
    #EbN0 = 1/(2*r) * (P/sigma**2)

    # overall rate of the code
    R = (L*logm - (nl-kl))/n
    
    return ber_amp, ber_ldpc, R

def amp_sim(L, M, σ_n, P, R, T, R_PA):
    # Compute the SNR, capacity, and n, from the input parameters
    #snr = P / σ_n**2 don't actually need snr and C
    #C = 0.5 * np.log2(1 + snr)
    # number of channel uses by the sparc code. 
    n = int(L*np.log2(M) / R)
    
    # Generate the power allocation
    # Pl = pa_iterative(L, L, σ_n, P, R_PA)
    # uniform power allocation across sections
    Pl = P/L * np.ones(L)
    
    # Generate random message in [0..M)^L
    tx_message = np.random.randint(0, M, L).tolist()
    
    # Generate the SPARC transform functions A.beta and A'.z
    Ab, Az = sparc_transforms(L, M, n)
    
    # Generate our transmitted signal X
    β_0 = np.zeros((L*M, 1))
    for l in range(L):
        β_0[l*M + tx_message[l]] = np.sqrt(n * Pl[l])
    x = Ab(β_0)

    # check that the power has been allocated uniformly. 
    print(np.mean(x**2))
    
    # Generate random channel noise and then received signal y
    z = np.random.randn(n, 1) * σ_n
    y = (x + z).reshape(-1, 1)
        
    # Run AMP decoding
    β = amp(y, σ_n, Pl, L, M, T, Ab, Az).reshape(-1)
    #The above is the section wise probabilities. I need to convert these to bitwise probabilities. 
    
    
    #print(bitwise_posterior(β, L, M))
    
    # Convert decoded beta back to a message
    rx_message = []
    for l in range(L):
        idx = np.argmax(β[l*M:(l+1)*M])
        rx_message.append(idx)
    
    # Compute fraction of sections decoded correctly
    correct = np.sum(np.array(rx_message) == np.array(tx_message)) / L
    
    # Compute BER note: np.sum will be deprecated soon, so look up alternative if this code stops working. 
    ber = np.sum(bin(a^b).count('1')
                 for (a, b) in zip(tx_message, rx_message))/(L*np.log2(M))
    
    # Compute Eb/N0
    EbN0 = 1/(2*R) * (P/σ_n**2)
    
    return ber
    '''return {
        "L": L, "M": M, "sigma_n": σ_n, "P": P, "R": R, "T": T,
        "snr": snr, "C": C, "n": n, "fc": correct, "R_PA": R_PA,
        "ber": ber, "EbN0": EbN0, "ser": 1-correct
    }'''



if __name__ == "__main__":
    '''c = np.array([0.2, 0.3, 0.1, 0.4, 0.6, 0.4, 0, 0])
    print(sp2bp(c, 2, 4))

    '''
    M = 512
    L = 512
    sigma = 1
    P = 4
    r_sparc = 1
    r_pa_sparc = 1
    T = 64
    sparcparams = SPARCParams(512, 512, 1, 4, 1, 1, 64)
    # nl is the number of bits in that will be LDPC bits. 
    # This is given by the no. bits per sections * the no. sections
    # Note the no. sections must be at least 8 to give something divisible by 24
    nl = np.log2(512) * 8 * 50
    print()
    # Can get from nl to z 
    z = int(nl/24)
    ldpcparams = LDPCParams('802.16', '1/2', z)

    (ber_amp, ber_ldpc, R) = amp_ldpc_sim(sparcparams, ldpcparams)
    print("ber_amp: ", ber_amp)
    print("ber_ldpc: ", ber_ldpc)
    print("R: ", R)


    '''
    #Code to plot the performance of the sparc code on it's own. 
    # fix rate
    R = 1

    σ_n = 1.0
    # shannon limit on snr. i.e. snr at capacity
    snrc = 2**(2*R)-1
    
    # Unsure what values to choose for T and R_PA. Just copied previous example.
    T = 64
    R_PA = R
    # store the error rate for each snr
    error_rate = []
    repeats = 1
    for snr in range(snrc,10):
        # calculate the new value of P to adjust the snr
        P = snr * σ_n**2
        error = []
        sparcparams = SPARCParams(512, 512, 1, P, 1, 1, 64)
        for i in range(repeats):
            ber = amp_ldpc_sim(sparcparams)[0]
            error.append(ber)
        aver_error = np.sum(error)
        error_rate.append(aver_error/repeats)
        
    plot(range(snrc,10), error_rate)
    xlabel('snr')
    title("Parameters: L=512, M=512, σ_n=1, R=1, T=64, R_PA=1")
    ylabel('BER')
    show()'''


